[theme]
background = "black"
primary = "white"
secondary = "white"
title = "green"
playing = "green"
playing_selected = "cyan"
playing_bg = "black"
highlight = "green"
highlight_bg = "black"
error = "white"
error_bg = "red"
statusbar = "green"
statusbar_progress = "green"
statusbar_bg = "black"
cmdline = "white"
cmdline_bg = "black"
