#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
	(>&2 echo "usage: $0 <recipient> <gpg encrypted file> <key>")
	exit 1
fi

recipient="$1"
gpg_file="$2"
key="$3"

gpg --list-keys "$recipient" >/dev/null 2>&1
if [ $? -ne 0 ]; then
	(>&2 echo "error: unknown recipient $recipient")
	exit 1
fi

if [ ! -f "$gpg_file" ]; then
	(>&2 echo "error: unable to open $gpg_file")
	exit 1
fi

code=$(gpg --quiet --batch --yes --recipient "$recipient" --decrypt "$gpg_file" | grep "^$key=" | cut -d= -f2)
if [ -z "$code" ]; then
	(>&2 echo "error: unable to find $key")
	exit 1
fi
oathtool --totp -b "$code"
