#!/bin/sh
if [ -n "$1" ]; then
	mul=$1
else
	mul=1
fi

amixer -q sset Master $((5*mul))%+

volume=$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')
enabled=$(amixer sget Master | awk -F"[][]" '/dB/ { print $6 }')

if [ x"$volume" != x"0%" ] && [ x"$enabled" = x"off" ]; then
	amixer -q sset Master toggle
fi
