#!/bin/sh

if [ -n "$BACKUP_PUBLIC_KEY" ]; then
	pub_key="$BACKUP_PUBLIC_KEY"
fi

if [ -n "$BACKUP_CONFIG_FILE" ]; then
	config_file="$BACKUP_CONFIG_FILE"
fi

if [ -n "$1" ] && [ -n "$2" ]; then
	pub_key="$1"
	config_file="$2"
fi

if [ -z "$pub_key" ] || [ -z "$config_file" ]; then
	echo "usage: $0 <BACKUP_PUBLIC_KEY | age public key> <BACKUP_CONFIG_FILE | config file>"
	exit 1
fi

backup_base_dir="/tmp/backup"
backup_dir="$backup_base_dir/$(date +%Y)/$(date +%m)/$(date +%d)"
timestamp=$(date +%s)

rm -rf "$backup_base_dir"
mkdir -p "$backup_dir"
chmod 700 "$backup_dir"

backup_file() {
	local in_file="$1"
	local out_file="$2.$timestamp.gz.age"
	local ssh_key="$3"
	local ssh_addr="$4"

	if [ -n "$ssh_key" ] && [ -n "$ssh_addr" ]; then
		scp -i "$ssh_key" "$ssh_addr":"$in_file" /dev/stdout \
			| gzip | age -r "$pub_key" >"$backup_dir/$out_file"
	else
		cat "$in_file" | gzip | age -r "$pub_key" >"$backup_dir/$out_file"
	fi
}

backup_dir() {
	local in_dir="$1"
	local dir=$(dirname $in_dir)
	local base=$(basename $in_dir)
	local out_file="$2.$timestamp.tar.gz.age"
	local ssh_key="$3"
	local ssh_addr="$4"

	if [ -n "$ssh_key" ] && [ -n "$ssh_addr" ]; then
		ssh -i "$ssh_key" "$ssh_addr" "tar cfz - -C $dir $base" \
			| age -r "$pub_key" >"$backup_dir/$out_file"
	else
		tar cfz - -C "$dir" "$base" | age -r "$pub_key" >"$backup_dir/$out_file"
	fi
}

backup_pg() {
	local user="$1"
	local pass="$2"
	local db="$3"
	local out_file="$4.$timestamp.gz.age"
	local ssh_key="$5"
	local ssh_addr="$6"

	if [ -n "$ssh_key" ] && [ -n "$ssh_addr" ]; then
		ssh -i "$ssh_key" "$ssh_addr" PGPASSWORD=$pass pg_dump -U "$user" -h "localhost" "$db" | \
			gzip | age -r "$pub_key" >"$backup_dir/$out_file"
	else
		PGPASSWORD=$pass pg_dump -U "$user" -h "localhost" "$db" | \
			gzip | age -r "$pub_key" >"$backup_dir/$out_file"
	fi
}

sync_dir() {
	local in_dir="$1"
	local dir=$(dirname $in_dir)
	local base=$(basename $in_dir)
	local out_dir="$2"
	local ssh_key="$3"
	local ssh_addr="$4"

	rsync -az -e "ssh -i $ssh_key" "$ssh_addr:$in_dir" "$out_dir"
}

rclone_copy() {
	local in_dir="$1"
	local out_dir="$2"

	if [ "$in_dir" = "__BACKUP_DIR__" ]; then
		in_dir="$backup_base_dir"
	fi

	rclone copy --progress "$in_dir" "$out_dir"
}

grep -q "^backup_file " $config_file
if [ $? -eq 0 ]; then
	echo "backing up files"
	grep "^backup_file " $config_file | while read _ in_file out_file ssh_key ssh_addr; do
		backup_file "$in_file" "$out_file" "$ssh_key" "$ssh_addr"
	done
fi

grep -q "^backup_dir " $config_file
if [ $? -eq 0 ]; then
	echo "backing up directories"
	grep "^backup_dir " $config_file | while read _ in_dir out_file ssh_key ssh_addr; do
		backup_dir "$in_dir" "$out_file" "$ssh_key" "$ssh_addr"
	done
fi

grep -q "^backup_pg " $config_file
if [ $? -eq 0 ]; then
	echo "backing up postgres databases"
	grep "^backup_pg " $config_file | while read _ user pass db out_file ssh_key ssh_addr; do
		backup_pg "$user" "$pass" "$db" "$out_file" "$ssh_key" "$ssh_addr"
	done
fi

grep -q "^sync_dir " $config_file
if [ $? -eq 0 ]; then
	echo "syncing directories"
	grep "^sync_dir " $config_file | while read _ in_dir out_dir ssh_key ssh_addr; do
		sync_dir "$in_dir" "$out_dir" "$ssh_key" "$ssh_addr"
	done
fi

grep -q "^rclone_copy " $config_file
if [ $? -eq 0 ]; then
	echo "rclone copy directories"
	grep "^rclone_copy " $config_file | while read _ in_dir out_dir; do
		rclone_copy "$in_dir" "$out_dir"
	done
fi

echo "cleaning up"
rm -rf "$backup_base_dir"
